### PR TITLE
DS-977 Into WIP (newer version of #50)

### PR DESCRIPTION
**Pull request by sugi-chan**
Creating a second pull request from my creevey clone into creevey WIP instead of master. 

I adjusted the version number as mentioned in the previous pull request to 0.4.0

Notes for comments in #50 
Files were almost all generated by sphinx as defaults (Makefile and make.bat are default generated). conf.py, contrib.rst, and index.rst are the only ones that should get changed since there is creevey info in those. I guess we can track them?

As far as deleting the md files, apparate has the md files in the gitrepo and the info in the hosted docs so I think it is alright to leave them.

### CODE REVIEW

**Comment by gsganden** [comment]
Cool. I'm a little unclear on how all this works. Can we have a quick chat on Monday?

**Comment by sugi-chan** [comment]
yeah, sounds good!

**Comment by gsganden** [comment]
I'd like to set it up so that we have `.md` files as the sources of truth for the documentation and the `.rst` files as autogenerated artifacts. Could we do that in this PR? It would be nice also to show the docstrings on readthedocs, but that can be a future ticket and PR.

**Comment by sugi-chan** [comment]
ok so check out the page [here](https://creevey-sugi.readthedocs.io/en/latest/index.html) if you like. I point read the docs at the added requirements file (it only has m2r which is used to read in the md files). Other than that I basically switched the index.rst and contrib.rst to just point to the readme.md and contrib/conduct md files.

**Comment by sugi-chan** [comment]
I think we can just wait on it since I don't think there is a huge rush.

**Pull request merged**
